//Bulletpoint Js File

//["0Title","1date","2uploader",3[["Common Tags"]"tag1","tag2","tag3","tag4"],"4Preview image",5["pdf file","size"],6["original file","size"],7["zip file","size"],8"pages",9"copyrights"]

var azArray = [
	/*0A*/[
		["Active transport",[["Biology"],"Movement in and out of cells"],["IGCSE"],["Introduction",["<b>Active transport:</b> Movement of particles through a cell membrane, ...","null"],["... from a region of <b>lower</b> concentration to a region of <b>higher</b> concentration ...","null"],["... against a <b>concentration gradient</b>, using energy released during <b>respiration</b>","From Znotes CIE IGCSE Biology - 3.3 Active Transport"]]]
		,["Anther---directTo---Formation of flowers",[["Biology"],"Reproduction in plants"],["IGCSE"]]
		,["Asexual reproduction",[["Biology"],"Sexual and Asexual reproduction"],["IGCSE"],["Introduction",["Asexual reproduction is the production of offspring from a single parent, which results in genetically identical offspring.","null"],["Only one parent is needed in asexual reproduction, and the offspring produced are genetically identical.","null"],["IMG---process_of_mitosis.jpg---375"],["&nbsp;&nbsp;- eg reproduction in bacteria, production of spores by fungi, and the formation of tubers in potatoes and bulbs in daffodils.","http://www.bbc.co.uk/education/guides/z2xg87h/revision"],["&nbsp;- No gamate required","null"],["&nbsp;- No fertilization","null"],["&nbsp;- Involves mitosis","null"],["&nbsp;- Genes from 1 parent","null"],["-->Gives identical offspring","From Socratic App - Asexual reproduction"]]]
		,["Animal cell - Liver cell",[["Biology"],"Cell structure"],["IGCSE"],["Introduction",["The main parts of an animal cell are the nucleus, cell membrane and cytoplasm.","null"],["IMG---animal_cell.png---304"],["Animal cell: ","null"],["1. <b>do not have cell walls</b>","null"],["2. <b>do not contain chloroplasts, so animals cannot carry out photosynthesis</b>","null"],["3. <b>may store carbohydrate as glycogen</b>","http://www.bbc.co.uk/education/guides/zr46fg8/revision/2"],["IMG---animal_cell_under_microscope.jpeg---800"],["Above is a picture of a animal cell (liver cell) under microscope.","null"]]]
		,["Arteries---directTo---Blood vessels",[["Biology"],"Transport in humans"],["IGCSE"]]
		,["Antigens---directTo---The immune system",[["Biology"],"Blood (Topic)"],["IGCSE"]]
		,["Antibodies---directTo---The immune system",[["Biology"],"Blood (Topic)"],["IGCSE"]]
		,["Amylase---directTo---Digestive enzymes",[["Biology"],"Digestive system (Topic)"],["IGCSE"]]
		,["Absorption",[["Biology"],"Digestive system (Topic)"],["IGCSE"],["Introduction",["<b>Absorption</b> is the movement of digested food molecules through ...","null"],["...  the wall of the intestine into the blood or lymph.","http://www.bbc.co.uk/education/guides/zwqycdm/revision/6"]]]
		,["Assimilation",[["Biology"],"Digestive system (Topic)"],["IGCSE"],["Introduction",["Assimilation is the movement of digested food molecules into ...","null"],["...  the cells of the body <b>where they are used</b>.","null"],["<b>For example:</b>","null"],[" - glucose is used in respiration to provide energy","null"],[" - amino acids are used to build new proteins","http://www.bbc.co.uk/education/guides/zwqycdm/revision/7"]]]
		,["Anti-diuretic hormone",[["Biology"],"Excretion in humans"],["IGCSE"],["Introduction",["The water content of the blood is controlled by a hormone called <b>ADH (anti-diuretic hormone)</b>.","null"],[" Different amounts of ADH are released into the <b>bloodstream</b> according to the <b>concentration</b> of the blood plasma.","https://www.bbc.co.uk/education/guides/zj7v4wx/revision/6"]]]
		,["Aerobic and anaerobic respiration",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Aerobic respiration",[["Biology"],"Aerobic and anaerobic respiration"],["IGCSE"],["Introduction",["<b>Respiration</b> involves chemical reactions that break down nutrient molecules in living cells to release energy.","null"],["<b>Aerobic respiration needs oxygen.</b>","null"],["It is the release of a relatively <b>large amount</b> of energy in cells by the <b>breakdown</b> of food substances in the presence of oxygen","https://www.bbc.co.uk/education/guides/zm6rd2p/revision/2"]]]
		,["Anaerobic respiration",[["Biology"],"Aerobic and anaerobic respiration"],["IGCSE"],["Introduction",["<b>Respiration</b> involves chemical reactions that break down nutrient molecules in living cells to release energy.","https://www.bbc.co.uk/education/guides/zm6rd2p/revision"],["Unlike aerobic respiration, anaerobic respiration <b>does not need oxygen</b>.","null"],["It is the <b>release</b> of a relatively small amount of energy in cells by ...","null"],["...  the breakdown of <b>food substances</b> in the <b>absence of oxygen</b>.","https://www.bbc.co.uk/education/guides/zm6rd2p/revision/2"]]]
		,["Auxin",[["Biology"],"Plant hormones"],["IGCSE"],["Introduction",["Auxin is ...","null"],[" - plant hormones or growth substances","null"],[" - controls tropisms","null"],[" - it is produced by cells at the tip of roots and shoots of plants","From Znotes CIE IGCSE Biology - 14.18 Tropic Responses"],["IMG---auxin.jpg---500"]]]
		,["Animal hormones",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Adrenaline---directTo---Hormones in human",[["Biology"],"Animal hormones"],["IGCSE"]]
		,["Amniotic sac---directTo---The developing embryo",[["Biology"],"Reproduction in humans"],["IGCSE"]]
		,["Amniotic fluid---directTo---The developing embryo",[["Biology"],"Reproduction in humans"],["IGCSE"]]
		,["Alleles",[["Biology"],"DNA and cell division"],["IGCSE"],["Introduction",["There are <b>pairs of chromosomes</b> in the nucleus of a body cell.","null"],["The chromosomes in a pair carry the same genes in the same places.","null"],["But there are different versions of the same gene.","null"],["IMG---dominant_and_recessive.jpg---550"],["<b>Alleles:</b> different versions of the same gene.","null"],["For example, the gene for eye colour has an allele for blue eye colour and an allele for brown eye colour.","null"],["For any gene, a person may have the same two alleles or two different ones.","https://www.bbc.co.uk/education/guides/zvb7hyc/revision/3"]]]
	],
	/*1B*/[
		["Biology",[["Study Set"],"Study Set"],["IGCSE"]]
		,["Blood (Topic)",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Blood",[["Biology"],"Blood (Topic)"],["IGCSE"],["Introduction",["Blood transports materials and heat around the body, and helps to protect against disease. It contains:","null"],["- plasma","null"],["- red blood cells","null"],["- white blood cells","null"],["- platelets","http://www.bbc.co.uk/education/guides/ztp9q6f/revision/1"]]]
		,["Biological molecules",[["Biology"],"Nutrients and Enzymes"],["IGCSE"],["Introduction",["<b>A nutrient</b> is a substance which is needed for growth, repair and metabolism.","null"],["The <b>three main</b> nutrients are:","null"],[" - carbohydrates","null"],[" - proteins","null"],[" - lipids (fats and oils)","null"],["These nutrients are all examples of organic chemicals.","null"],["This means that they all contain <b>carbon atoms</b>, <b>covalently bonded</b> to the atoms of other elements.","http://www.bbc.co.uk/education/guides/z8wsgk7/revision/4"]]]
		,["Blood vessels",[["Biology"],"Transport in humans"],["IGCSE"],["Introduction",["Blood vessel is any of the vessels through which the blood circulates.","null"],["There are three types of blood vessels: arteries, veins and capillaries.","null"]]]
		,["Bile---directTo---Digestive system",[["Biology"],"Digestive system (Topic)"],["IGCSE"]]
		,["Breast feeding---directTo---The developing embryo",[["Biology"],"Reproduction in humans"],["IGCSE"]]


	],
	/*2C*/[
		["Chloroplasts",[["Biology"],"Plant nutrition (Photosynthesis)"],["IGCSE"],["Introduction",["Chloroplasts are organelles found in plant cells and in algae.","From Socratic App - Light Absorption in Chloroplasts"],["Contains the green pigment chlorophyll; the site of photosynthesis.","http://www.bbc.co.uk/education/guides/zq239j6/revision/1"]]]
		,["Cross-pollination---directTo---Pollination",[["Biology"],"Reproduction in plants"],["IGCSE"]]
		,["Cells",[["Biology"],"Cell structure"],["IGCSE"],["Introduction",["All living organisms are made up of units called <b>cells</b>.","null"],["Both animal and plant cells have <b>cell surface membrane</b>, <b>cytoplasm</b> and a <b>nucleus</b>","null"],["IMG---animal_cell.png---304"],["In addition, plant cells have a <b>cellulose cell wall</b>, a <b>vacuole</b> and may have <b>chloroplasts</b>","Complete Biology for Cambridge IGCSE Third Edition P17"],["IMG---animal_cell.png---304","null"]]]
		,["Cell structure",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Cells, tissues and organs",[["Biology"],"Cell structure"],["IGCSE"],["Introduction",["In order of increasing complexity, multicellular organisms consist of:","null"],["organelles → cells → tissues → organs → organ systems","http://www.bbc.co.uk/education/guides/zgcxsbk/revision/1"]]]
		,["Calculating Magnification",[["Biology"],"Cell structure"],["IGCSE"],["Introduction",["The magnification of a biological specimen is calculated using this equation:","null"],["<i><u>magnification = measured size / actual size</u></i>","http://www.bbc.co.uk/education/guides/zgcxsbk/revision/4"]]]
		,["Concentration gradient",[["Biology"],"Movement in and out of cells"],["IGCSE"],["Introduction",["When sucrose is dissolved in water:","null"],["- the soluteis sucrose","null"],["- water is the solvent","null"],["The <b>more particles there are</b> in a certain volume, the <b>more concentrated</b> those particles are.","http://www.bbc.co.uk/education/guides/zc9tyrd/revision/1"]]]
		,["Capillaries---directTo---Blood vessels",[["Biology"],"Transport in humans"],["IGCSE"]]
		,["Controlling plant growth",[["Biology"],"Plant hormones"],["IGCSE"],["Introduction",["<b>Synthetic plant hormones</b> are used to control plant growth.","null"],["<b>For example,</b> rooting powder contains growth hormones that make stem cuttings develop roots quickly.","https://www.bbc.co.uk/education/guides/z98p34j/revision/5"]]]
		,["Coronary heart disease",[["Biology"],"Transport in humans"],["IGCSE"],["Introduction",["The coronary arteries supply blood to the heart muscle.","null"],["IMG---coronary_heart_disease.jpg---650"],[" These may become blocked by a <b>build-up</b> of <b>fatty plaques</b> containing <b>cholesterol</b>, resulting in coronary heart disease.","https://www.bbc.co.uk/education/guides/zhnk7ty/revision/6"]]]


	],
	/*3D*/[
		["Diffusion",[["Biology"],"Movement in and out of cells"],["IGCSE"],["Introduction",["<b>Diffusion:</b> movement of molecules from ...","null"],["... a region of <b>high concentration</b> to a region of <b>low concentration</b> ...","null"],["... down the <i>concentration gradient</i>.","null"],["This results in <b>random movement</b> of molecules until equilibrium is reached","From Znotes CIE IGCSE Biology - 3.2 Osmosis"]]]
		,["Double circulation---directTo---The circulatory system",[["Biology"],"Transport in humans"],["IGCSE"]]
		,["Digestive system (Topic)",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Digestive system",[["Biology"],"Digestive system (Topic)"],["IGCSE"],["Introduction",["IMG---structure_of_digestive_system.jpg---500"]]]
		,["Digestive enzymes",[["Biology"],"Digestive system (Topic)"],["IGCSE"],["Introduction",["Digestion is the breakdown of <b>large, insoluble food</b> molecules into ...","null"],["... small, water-soluble molecules using mechanical and chemical processes.","null"],["<b>Mechanical digestion includes:</b>","null"],[" - chewing in the mouth","null"],[" - churning in the stomach","null"],["Chemical digestion involves enzymes.","null"],["These are proteins that function as biological catalysts.","http://www.bbc.co.uk/education/guides/zwqycdm/revision/4"]]]
		,["DNA and cell division",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["DNA, Genes and Chromosomes",[["Biology"],"DNA and cell division"],["IGCSE"],["Introduction",["<b>DNA</b> carries genetic code that determines <b>characteristics</b> of a living organism.","null"],["IMG---dna.gif---500"],["<b>Chromosomes</b> are made from DNA.","null"],["<b>Genes</b> are <b>short sections</b> of DNA.","https://www.bbc.co.uk/education/guides/zvb7hyc/revision"]]]
		,["Dominant---directTo---Monohybrid crosses",[["Biology"],"Inheritance"],["IGCSE"]]
		,["DNA (Topic)",[["Study Set - Topic"],"Biology"],["KS3"]]
		,["DNA",[["Biology"],"DNA (Topic)"],["KS3"],["Introduction",["Genetic information is passed from one generation to the next.","null"],["This is called heredity and why we resemble our parents.","null"],["The genetic information itself is contained in a complex molecule called DNA.","https://www.bbc.co.uk/education/guides/zp7thyc/revision"]]]

	],
	/*4E*/[
		["Enzymes",[["Biology"],"Nutrients and Enzymes"],["IGCSE"],["Introduction",["An enzyme is a protein that functions as a <b>biological catalyst</b>","null"],[" – a substance that <b>speeds up</b> a chemical reaction without being changed by the reaction.","http://www.bbc.co.uk/education/guides/z8wsgk7/revision/5"]]]
		,["Egestion",[["Biology"],"Digestive system (Topic)"],["IGCSE"],["Introduction",["The <b>small intestine</b> absorbs most of the water in the contents of the gut.","null"],["By the time the <b>contents</b> reach the end of the small intestine, ...","null"],["... most of the <b>digested food</b> has also been <b>absorbed</b>.","http://www.bbc.co.uk/education/guides/zwqycdm/revision/7"]]]
		,["Excretion",[["Biology"],"Excretion in humans"],["IGCSE"],["Introduction",["<b>Excretion is the removal of the following substances:","null"],[" - toxic materials","null"],[" - waste products of metabolism","null"],[" - excess substances from organisms","null"],["Excretion is not the same as <b>egestion</b> - which is ...","null"],["the passing out of undigested food through the anus as faeces.","http://www.bbc.co.uk/education/guides/zj7v4wx/revision/1"]]]
		,["Excretion in humans",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Effects of exercise on breathing",[["Biology"],"The respiratory system (Topic)"],["IGCSE"],["Introduction",["Physical activity <b>increases</b> the <b>breathing rate</b> – <b>more breaths per minute</b>, and the tidal volume – <b>more air per breath</b>","From Znotes CIE Biology - Breathing"]]]
		,["Effects of smoking",[["Biology"],"The respiratory system (Topic)"],["IGCSE"],["Introduction",["<b>Smoking</b> can cause lung disease, heart disease and certain cancers.","null"],["<b>Nicotine</b> is the addictive substance in tobacco.","null"],["It quickly reaches the <b>brain</b> and creates a <b>dependency</b> so that smokers become addicted.","https://www.bbc.co.uk/education/guides/z6h4jxs/revision/5"]]]

	],
	/*5F*/[
		["Formation of flowers",[["Biology"],"Reproduction in plants"],["IGCSE"],["Introduction",["Flowers are important in the sexual reproduction of plants.","null"],["They produce male sex cells (pollen grains) and female sex cells (contained in the ovules).","null"],["These must meet for reproduction to begin - a process called pollination.","http://www.bbc.co.uk/education/guides/z2xg87h/revision/2"],["IMG---structure_of_flowers.jpg---720"],["The major parts of flower includes the following:","null"],["<b>Carpel: </b>Stigma, Style, ovary","null"],["<b>Stamen: </b>Anther, filament","null"],["<b>Petals: </b>Colorful","null"],["<b>Sepals: </b>Modified leaves","From Socratic App - Angiosperm Reproduction And Flower Structure"]]]

		,["Fertilisation in plants",[["Biology"],"Reproduction in plants"],["IGCSE"],["Introduction",["Pollination is complete once the pollen released from an anther has landed on the stigma if the same or another flower.","null"],["<b>The next step is fertilisation.</b>","From Complete Biology for Cambridge IGCSE Third Editon P166"],["IMG---structure_of_flowers.jpg---720"]]]

		,["Fertilisation in human",[["Biology"],"Reproduction in humans"],["IGCSE"],["Introduction",["<b>Fertilisation:</b> fusion of the nucleus of a <b>male gamete</b> with the nucleus of a <b>female gamete</b>, producing a new cell called a <b>zygote</b>.","null"],["This then matures into an <b>embryo</b>.","https://www.bbc.co.uk/education/guides/z7mbkqt/revision/4"],["IMG---fertilisation_gamate.jpg---600"]]]
	],
	/*6G*/[
		["Germination in plants",[["Biology"],"Reproduction in plants"],["IGCSE"],["Introduction",["<b>Germination is a process</b>, controlled by enzymes, in which the seed begins to develop into a new young plant.","null"],["Germinating seeds use their food stores until the seedlings can produce their own food by photosynthesis.","http://www.bbc.co.uk/education/guides/z2xg87h/revision/5"],["<b>A seed has three main parts:</b>","null"],["IMG---germination_cross_section.png---304"],["<b>Embryo</b> – the young root and shoot that will become the adult plant","null"],["<b>Food store</b> – starch for the young plant to use until it is able to carry out photosynthesis","null"],["<b>Seed coat</b> – a tough protective outer covering","null"]]]
		,["Gas exchange in lungs",[["Biology"],"The respiratory system (Topic)"],["IGCSE"],["Introduction",["<b>Gas exchange</b> in the lungs happens in the <b>alveoli</b>.","null"],["Some of the <b>features</b> of alveoli include:","null"],["IMG---gas_exchange.jpg---500"],[" - thin walls (just one cell thick)","null"],[" - large surface area","null"],[" - moist surface","null"],[" - many blood capillaries","https://www.bbc.co.uk/education/guides/z6h4jxs/revision/3"]]]
		,["Genotype---directTo---Monohybrid crosses",[["Biology"],"Inheritance"],["IGCSE"]]

	],
	/*7H*/[

		["Hermaphrodite",[["Biology"],"Reproduction in plants"],["IGCSE"],["Introduction",["Most plants are hermaphrodite, that is, they have male and female sexual parts on the same individual.","null"],[" - which means the male gamates only have to travel a short distance to the female gametes.","null"]]]
		,["Heart",[["Biology"],"Transport in humans"],["IGCSE"],["Introduction",["The heart is a muscular organ","null"],["Its function is to pump blood","null"]]]
		,["Homeostasis (Topic)",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Homeostasis",[["Biology"],"Homeostasis (Topic)"],["IGCSE"],["Introduction",["Homeostasis is the maintenance of a constant internal environment","null"],["The nervous system and hormones are responsible for this","null"],["Example: the concentration of carbon dioxide in the blood being carefully controlled.","https://www.bbc.co.uk/education/guides/z4khvcw/revision/1"]]]
		,["Hormones in human",[["Biology"],"Animal hormones"],["IGCSE"],["Introduction",["<b>Hormones: </b>a chemical substance, produced by a <b>gland</b> and carried by the <b>blood</b>, which <b>alters the activity</b> of more specific target organs <i style='opacity: 0.6;'>(and is then destroyed by the liver)</i>.","https://www.bbc.co.uk/education/guides/z98p34j/revision"]]]
		,["Homozygous---directTo---Monohybrid crosses",[["Biology"],"Inheritance"],["IGCSE"]]
		,["Heterozygous---directTo---Monohybrid crosses",[["Biology"],"Inheritance"],["IGCSE"]]

	],
	/*8I*/[
		["Insect-pollinated flowers---directTo---Pollination",[["Biology"],"Reproduction in plants"],["IGCSE"]]
		,["Ingestion",[["Biology"],"Digestive system (Topic)"],["IGCSE"],["Introduction",["Food enters the digestive system <b>through the mouth</b>.","null"],["This process is called <b>ingestion</b>.","null"],["Once in the mouth, the food is chewed to form a ball of food called a <b>bolus</b>.","null"],["This passes down the <b>oesophagus</b> and into the stomach.","http://www.bbc.co.uk/education/guides/zwqycdm/revision/3"],["IMG---structure_of_digestive_system.jpg---500"]]]
		,["Inhaled and exhaled air---directTo---Gas exchange in lungs",[["Biology"],"The respiratory system (Topic)"],["IGCSE"]]
		,["Inheritance of biological gender",[["Biology"],"Inheritance"],["IGCSE"],["Introduction",["Human body cells have <b>23 pairs of chromosomes</b> in the nucleus.","null"],["<b>One of these pairs</b> controls the inheritance of <b>biological gender</b> <I style='opacity: 0.6;'>(whether offspring are male or female)</I>","https://www.bbc.co.uk/education/guides/z3g2pv4/revision/2"]]]
		,["Inheritance",[["Study Set - Topic"],"Biology"],["IGCSE"]]


	],
	/*9J*/[],
	/*10K*/[
		["Kidney",[["Biology"],"Excretion in humans"],["IGCSE"],["Introduction",["The inner part of the kidney is called the <b>medulla</b> and ...","null"],["... the outer part is the <b>cortex</b>.","null"],["IMG---kidney.jpg---550"],["A <b>renal artery</b> carries blood to the <b>kidney</b> and a renal vein carries it <b>away</b>.","https://www.bbc.co.uk/education/guides/zj7v4wx/revision/4"]]]
	],
	/*11L*/[
		["Leaf Structure",[["Biology"],"Plant nutrition (Photosynthesis)"],["IGCSE"],["Introduction",["The leaf structure consist of:","null"],["Upper epidermis","null"],["- Cuticle","null"],["IMG---leaf_structure.jpg---600"],["Mesophyll layer","null"],[" - Palisade mesophyll","null"],[" - Spongy mesophyll : Xylem and Phloem","null"],["Lower epidermis","null"],[" - Stomata","null"]]]
		,["Lymphocytes---directTo---The immune system",[["Biology"],"Blood (Topic)"],["IGCSE"]]
		,["Lipases---directTo---Digestive enzymes",[["Biology"],"Digestive system (Topic)"],["IGCSE"]]
	],
	/*12M*/[
		["Meiosis",[["Biology"],"DNA and cell division"],["IGCSE"],["Introduction",["Meiosis is the type of cell division that produces gametes.","null"],["A human body cell contains 46 chromosomes arranged in 23 pairs.","null"],["Human gametes are haploid","null"],[" – so their nucleus only contains a single set of 23 unpaired chromosomes.","http://www.bbc.co.uk.edgesuite.net/education/guides/zvb7hyc/revision/5"]]]
		,["Mitosis",[["Biology"],"DNA and cell division"],["IGCSE"],["Introduction",["In mammals, body cells are diploid. The chromosomes need to be copied exactly so that new cells can be produced for:","null"],["- Growth","null"],["- Repair to damaged tissue","null"],["- Replacement of worn-out cells","null"]]]
		,["Movement in and out of cells",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Maltase---directTo---Digestive enzymes",[["Biology"],"Digestive system (Topic)"],["IGCSE"]]
		,["Menstrual Cycle",[["Biology"],"Reproduction in humans"],["IGCSE"],["Introduction",["The menstrual cycle is a recurring process which takes around <b>28 days</b>.","null"],["IMG---menstrual_cycle.jpg---600"],["During the process, the <b>lining of the uterus</b> is prepared for <b>pregnancy</b>.","null"],["If pregnancy <b>doesn't happen</b>, the lining is then <b>shed</b>.","null"],["This is known as <b>menstruation</b>.","https://www.bbc.co.uk/education/guides/z7mbkqt/revision/3"]]]
		,["Monohybrid crosses",[["Biology"],"Inheritance"],["IGCSE"],["Introduction",["A <b>monohybrid cross</b> shows how a single trait is passed on from parents to offspring.","null"],["Using the <b>genotypes</b> of the parents, we can predict the <b>genotypes and phenotypes</b> of their offspring.","From Socratic App - Monohybird Crosses"],["IMG---monohybird_crosses.png---665"],["IMG---monohybird_crosses_2.png---667"],["-> Examples of monohybird crosses","null"]]]

	],
	/*13N*/[
		["Nutrients and Enzymes",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Nephron",[["Biology"],"Excretion in humans"],["IGCSE"],["Introduction",["Urine is produced in microscopic structures in the kidney called <b>nephrons</b>.","null"],["IMG---nephron.jpg---650"],["Each kidney contains around a <b>million nephrons</b>.","https://www.bbc.co.uk/education/guides/zj7v4wx/revision/5"]]]
		,["Nervous control",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Nerve impulse---directTo---Types of neurons",[["Biology"],"Nervous control"],["IGCSE"]]
	],
	/*14O*/[
		["Ovary in plants---directTo---Formation of flowers",[["Biology"],"Reproduction in plants"],["IGCSE"]]
		,["Osmosis",[["Biology"],"Movement in and out of cells"],["IGCSE"],["Introduction",["<b>Osmosis:</b> Movement of water molecules from ...","null"],["... a region of <b>high</b> water potential to a region of <b>low</b> water potential, ...","null"],["... through a <i>partially permeable membrane</i> <i style='opacity: 0.6;'>(They let some substances pass through them, but not others.)</i>","From Znotes CIE IGCSE Biology - 3.2 Osmosis"]]]
		,["Oxygen debt---directTo---Anaerobic respiration",[["Biology"],"Aerobic and anaerobic respiration"],["IGCSE"]]


	],
	/*15P*/[
		["Petal---directTo---Formation of flowers",[["Biology"],"Reproduction in plants"],["IGCSE"]]
		,["Plasma---directTo---Blood",[["Biology"],"Blood (Topic)"],["IGCSE"]]
		,["Platelets---directTo---Blood",[["Biology"],"Blood (Topic)"],["IGCSE"]]
		,["Photosynthesis",[["Biology"],"Plant nutrition (Photosynthesis)"],["IGCSE"],["Introduction",["Photosynthesis is a process done by plants (as well as algae and some other prokaryotes) that converts energy from the sun into a usable form of energy, called glucose.","From Socratic App - Photosynthesis Overview"],["IMG---Photosynthesis.jpg---550"],[" - light energy is absorbed by chlorophyll","null"],[" - absorbed light energy is used to convert carbon dioxide (from the air) and water (from the soil) into a sugar called glucose","null"],["IMG---photosynthesis_Equation.png---375"],[" - oxygen is released as a by-product","http://www.bbc.co.uk/education/guides/zq239j6/revision/1"]],["Factors affecting photosynthesis",["Light intensity","null"],[" - Without enough light, a plant cannot photosynthesise very quickly - even if there is plenty of water and carbon dioxide. Increasing the light intensity will boost the rate of photosynthesis.","null"],["IMG---lightIntensity_photosynthesis.png---304","null"],["Carbon dioxide concentration","null"],[" - Even if there is plenty of light, a plant cannot photosynthesise if there is insufficient carbon dioxide.","null"],["IMG---carbondioxide_photosynthesis.png---304","null"],["Temperature","null"],[" - If it gets too cold, the rate of photosynthesis will decrease. Plants cannot photosynthesise if it gets too hot.","null"],["IMG---temperature_photosynthesis.png---304","null"]],["BBC Bitesize - Photosynthesis",["AHREF---http://www.bbc.co.uk/education/guides/zq239j6/revision/1","null"],["<iframe src='http://www.bbc.co.uk/education/guides/zq239j6/revision/1' width='100%' height='600' scrolling='yes' class='iframe'></iframe>","null"]],["Wikipedia - Photosynthesis",["AHREF---https://en.m.wikipedia.org/wiki/Photosynthesis","null"],["<iframe src='https://en.m.wikipedia.org/wiki/Photosynthesis' width='100%' height='600' scrolling='yes' class='iframe'></iframe>","null"]]]
		,["Pollination",[["Biology"],"Reproduction in plants"],["IGCSE"],["Introduction",["Pollination is the transfer of pollen from the male part of plants (anther) to the female part of plants (stigma) for reproduction.","null"],["Plants must be from the same species for successful fertilization.","From Socratic App - Pollination"]]]
		,["Palisade mesophyll---directTo---Leaf Structure",[["Biology"],"Plant nutrition (Photosynthesis)"],["IGCSE"]]
		,["Plant cell - Palisade cell",[["Biology"],"Cell structure"],["IGCSE"],["Introduction",["Plant cells contain <b>nucleus, cell membrane and cytoplasm</b>.","null"],["IMG---plant_cell.png---304"],["Also contain which <b>animal cells don't have</b>: ","null"],["1. <b>Chloroplasts</b>","null"],["2. <b>Cellulose cell wall</b>","null"],["3. <b>Permanent vacuole</b>","[1] http://www.bbc.co.uk/education/guides/zr46fg8/revision/3"],["IMG---plant_cell_under_microscope.jpg---640"],["Above is a picture of a plant cell (Palisade cell) under microscope.","null"]]]
		,["Pathogens---directTo---The immune system",[["Biology"],"Blood (Topic)"],["IGCSE"]]
		,["Phagocytosis---directTo---The immune system",[["Biology"],"Blood (Topic)"],["IGCSE"]]
		,["Phagocytes---directTo---The immune system",[["Biology"],"Blood (Topic)"],["IGCSE"]]
		,["Plant nutrition (Photosynthesis)",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Proteases---directTo---Digestive enzymes",[["Biology"],"Digestive system (Topic)"],["IGCSE"]]
		,["Plant hormones",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Plant tropisms",[["Biology"],"Plant hormones"],["IGCSE"],["Introduction",["Plants need light and water for photosynthesis.","null"],["They have developed responses called <b>tropisms</b> to ...","null"],["... help make sure they <b>grow towards</b> sources of <b>light and water</b>.","https://www.bbc.co.uk/education/guides/z98p34j/revision/3"]]]
		,["Placenta and umbilical cord---directTo---The developing embryo",[["Biology"],"Reproduction in humans"],["IGCSE"]]
		,["Phenotype---directTo---Monohybrid crosses",[["Biology"],"Inheritance"],["IGCSE"]]

	],
	/*16Q*/[],
	/*17R*/[
		["Reproduction in plants",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Root hair cell",[["Biology"],"Transport in plants"],["IGCSE"],["Introduction",["Plants absorb water from the soil by osmosis. Root hair cells are adapted for this by having a large surface area to speed up osmosis.","http://www.bbc.co.uk/schools/gcsebitesize/science/add_edexcel/organism_energy/photosynthesisrev5.shtml"],["IMG---rootHairCell.jpeg---327","null"],["A specialised cell that increases the surface area of the root epidermis to improve the uptake of water and minerals.","http://www.bbc.co.uk.edgesuite.net/education/guides/zps82hv/revision/3"]],["Structure",["The root hair cells has a special structure to help it absorb water from the soil efficiently.","null"],["1. Has a long thin extension","null"],[" - which provides a large surface area for absorption of water.","null"],["IMG---th.jpg---272","null"],["2. Large vacuole","null"],[" - The root hair cell has a large vacuole to maximize the amount of water capacity of the cell; thus, the cell is able to absorb and store more water.","null"],["3. Cell sap ","null"],["- The cell sap of the root hair cell has a lower water potential than the water in the soil. Thus, the water from the soil moves into the cell via osmosis.","http://www.answers.com/Q/What_is_the_structure_of_root_hair_cells"]],["Q: How water is absorbed into root hairs from soil",["Water and minerals flow into the cell sap of root hair cell","null"],["by osmosis because the soil water has a higher water potential than the cytoplasm of the root hair cell, so the water moves down a water potential gradient.","null"]],["Function",["The function of root hair cell is to collect water and mineral nutrients present in the soil and take this solution up through the roots to the rest of the plant.","null"],["As root hair cells do not carry out photosynthesis they do not contain chloroplasts.","n.wikipedia.org/wiki/Root_hair"]],["Relevant Videos",["VIDEO---https://www.youtube.com/watch?v=MT8Iywvc6js---diffusion and active uptake in root hair cells---From Youtube","null"],["VIDEO---https://www.youtube.com/watch?v=ky8XeCGtX6k---Transport in Plants - Absorption of water---From Youtube","null"]],["BBC Bitesize",["AHREF---http://www.bbc.co.uk.edgesuite.net/education/guides/zps82hv/revision/3","null"],["<iframe src='http://www.bbc.co.uk.edgesuite.net/education/guides/zps82hv/revision/3' width='100%' height='600' scrolling='yes' class='iframe'></iframe>","null"]]]
		,["Red blood cells",[["Biology"],"Blood (Topic)"],["IGCSE"],["Introduction",["<b>Red blood cells</b> transport oxygen for <b>aerobic respiration</b>.","null"],["They must be able to absorb oxygen in the lungs, pass through narrow blood vessels, and release oxygen to respiring cells.","null"],["They must be able to absorb oxygen in the lungs, pass through narrow blood vessels, and release oxygen to respiring cells.","http://www.bbc.co.uk/education/guides/ztp9q6f/revision/2"]]]
		,["Receptors and effectors",[["Biology"],"Nervous control"],["IGCSE"],["Introduction",["The diagram below summarises how information flows from <b>receptors</b> to <b>effectors</b> in the nervous system.","https://www.bbc.co.uk/education/guides/zkdnb9q/revision/2"],["IMG---receptors_to_effectors.jpg---500"]]]
		,["Reflex actions",[["Biology"],"Nervous control"],["IGCSE"],["Introduction",["<b>Reflex action:</b> a way for the body to automatically and rapidly <b>respond</b> ...","null"],["... to a stimulus to <b>minimise</b> any further damage to the body.","null"],["It <b>follows</b> this general sequence and doesn't <b>involve the brain</b>:","null"],["stimulus → receptor → sensory neurone → relay neurone → motor neurone → effector → response","https://www.bbc.co.uk/education/guides/zkdnb9q/revision/3"]]]
		,["Reflex arc---directTo---Reflex actions",[["Biology"],"Nervous control"],["IGCSE"]]
		,["Reproduction in humans",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Recessive---directTo---Monohybrid crosses",[["Biology"],"Inheritance"],["IGCSE"]]
		,["Respiration (Topic)",[["Study Set - Topic"],"Biology"],["KS3"]]
		,["Respiration",[["Biology"],"Respiration (Topic)"],["KS3"],["Introduction",["<b>Respiration: </b> a chemical reaction that happens in all living cells, including plant cells and animal cells.","null"],["<b>Energy is needed for life processes such as:</b>","null"],[" - growth and repair","null"],[" - movement","null"],[" - control of body temperature in mammals","https://www.bbc.co.uk/education/guides/zq349j6/revision/1"]]]

	],
	/*18S*/[
		["Stamen---directTo---Formation of flowers",[["Biology"],"Reproduction in plants"],["IGCSE"]]
		,["Stigma---directTo---Formation of flowers",[["Biology"],"Reproduction in plants"],["IGCSE"]]
		,["Sepal---directTo---Formation of flowers",[["Biology"],"Reproduction in plants"],["IGCSE"]]
		,["Self-pollination---directTo---Pollination",[["Biology"],"Reproduction in plants"],["IGCSE"]]
		,["Seed Coat Testa Cotyledons Seed leaf Endosperm Plumule Radicle Micropyle---directTo---Germination in plants",[["Biology"],"Reproduction in plants"],["IGCSE"]]
		,["Sexual reproduction",[["Biology"],"Sexual and Asexual reproduction"],["IGCSE"],["Introduction",["Sexual reproduction is the process of two individuals contributing to the formation of a new organism.","null"],["During sexual reproduction, gametes fuse together in a process called fertilization.","null"],["IMG---meiosis.jpg---467"],[" - Requires 2 parents (male + female)","null"],[" - Involves the fusion of gametes (eggs + sperm)","null"],[" - Involves meiosis","null"],[" - Offspring reveives genes from both parents (may causes genetic variation)","null"],[" - Done by multicellular eukaryotes","From Socratic App - Sexual reproduction"]]]
		,["Stomata",[["Biology"],"Transport in plants"],["IGCSE"],["Introduction",["The stomata are pores (tiny holes) in leaves.","null"],["They are mainly present in the lower epidermis.","null"],[" - This surface is less exposed to the Sun's radiation so the evaporation of water is kept to a minimum.","null"],[" - The stomata can be closed when no Carbon Dioxide intake is needed (in the dark, for example)","null"],["They are responsible for gas exchange.","http://www.answers.com/Q/What_is_stomata"]],["Function",["1. It helps in exchange of gases","null"],[" - Carbon Dioxode and water vapour diffuse in and out of the leaf","null"],["2. It helps the plant for respiration","null"],["IMG---Stomate-intro.jpg---900","null"],["3. It protects the plant from burning by sun","null"],[" - by providing moisture during too hot weather.","null"],["4. It help the plant in excretion by removing excesss water from plant's body","https://socratic.org/questions/what-is-the-stomata?from_app=1"]],["Adaptations",["Turgid","null"],[" - When a plant has plenty of water, the guard cells become turgid.","null"],[" - The cell wall on the inner surface is very thick, so it cannot stretch as much as the outer surface.","null"],[" - So as the guard cells swell up, they curve away from each other, opening the stomata.","null"],["IMG---stomata.jpg---720","null"],["Faccid","null"],[" - When a plant is short of water, the guard cells become flaccid, closing the stoma","null"]],["Bitesize - Stomata",["AHREF---http://www.bbc.co.uk/education/guides/zps82hv/revision/3","null"],["<iframe src='http://www.bbc.co.uk/education/guides/zps82hv/revision/3' width='100%' height='600' scrolling='yes' class='iframe'></iframe>","null"]],["Wikipedia - Stomata",["AHREF---https://en.m.wikipedia.org/wiki/Stoma","null"],["<iframe src='https://en.m.wikipedia.org/wiki/Stoma' width='100%' height='600' scrolling='yes' class='iframe'></iframe>","null"]]]
		,["Spongy mesophyll---directTo---Leaf Structure",[["Biology"],"Plant nutrition (Photosynthesis)"],["IGCSE"]]
		,["Specialised cells",[["Biology"],"Cell structure"],["IGCSE"],["Introduction",["Many cells are specialised.","null"],["They have structures that are adapted for their function","null"],["For example, muscle cells bring parts of the body closer together.","null"],["They contain protein fibres that can contract when energy is available, making the cells shorter.","http://www.bbc.co.uk/education/guides/zgcxsbk/revision/3"]]]
		,["Sexual and Asexual reproduction",[["Study Set - Topic"],"Biology"],["IGCSE"]]


	],
	/*19T*/[

		["Transpiration stream---directTo---Transpiration",[["Biology"],"Transport in plant"],["IGCSE"]]
		,["The immune system",[["Biology"],"Blood (Topic)"],["IGCSE"],["Introduction",["The immune system prevents, detects and stops infection within the organisms","null"],["<b>The immune system has many parts:</b>","null"],["- Lymphocytes","null"],["- Antibodies","null"],["- Phagocytes","http://www.bbc.co.uk/education/guides/ztp9q6f/revision/4"],["Together they kill the pathogens which invade the body or organisms.","null"]]]
		,["Transport in plants",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["Translocation",[["Biology"],"Transport in plants"],["IGCSE"],["Introduction",["Translocation is the movement of sucrose and other organic materials from one place to another within the plant body, primarily through the phloem.","null"],["Concentration (pressure) gradients drive this process.","http://science.halleyhosting.com/sci/ibbio/plants/notes/transloc.htm"],["IMG---translocation.jpg---638","null"],["In general, this happens between where these substances are made (the sources) and where they are used or stored (the sinks).","http://www.bbc.co.uk/education/guides/zps82hv/revision/1"]],["Differences between tranpiration and translocation",["IMG---difference.jpg---795","null"]],["Process",["Translocation typically begins in any plant location where sucrose is in high concentration.","null"],["There is a lower sucrose concentration in the sieve tubes (of the phloem).","null"],["IMG---phloem.jpg---270","null"],["This concentration or pressure difference causes the sucrose to diffuse toward and into the phloem of the leaf and hence to the phloem of the stem (where there is even less sucrose).","null"]],["BBC Bitesize",["AHREF---http://www.bbc.co.uk/education/guides/zps82hv/revision/1","null"],["<iframe src='http://www.bbc.co.uk/education/guides/zps82hv/revision/1' width='100%' height='600' scrolling='yes' class='iframe'></iframe>","null"]],["Relevant Videos",["VIDEO---https://www.youtube.com/watch?v=G2btL5NyGjU---IGCSE - Translocation---From Youtube","null"],["VIDEO---https://www.youtube.com/watch?v=tAf7kV9GHDw---Plant Biology: Transpiration and Translocationl---From Youtube","null"]]]
		
		,["Transpiration",[["Biology"],"Transport in plants"],["IGCSE"],["Introduction",["IMG---transpiration.png---624","null"],["Evaporation of water at the surfaces of the spongy mesophyll cells in leaves, followed by loss of water vapour through the stomata.","null"]],["Process",["1. Plants take in water from their roots through the process of osmosis [from the soil (high water potential) into the root cells (lower water potential)].","null"],["2. Water is pulled up from the roots in the xylem as a column of water","null"],[" - due to the tension caused by water loss from the leaves and the cohesion between the water molecules.","null"],["IMG---process_of_transpiration.jpg---397","null"],["3. Stomata allow the uptake of CO2 for photosynthesis.","null"],["  - When stomata are open, water evaporated from the spongy mesophyll can diffuse out of the leaf down the water potential gradient.","null"],["REMEMBER: As water leaves the plant, this creates a suctioning effect on the water in the xylem vessels by the leaves","From Socratic - Xylem and Phloem"]],["Functions",["• Transporting mineral ions","null"],["• Providing water to keep cells turgid in order to support the plant","null"],["• Providing water to leaf cells for photosynthesis","null"],["• Keeping the leaves cool by evaporation","null"]],["Factors affecting rate",["IMG---rate_of_transpiration.png---975","null"],["- Temperature","null"],["- Humidity","null"],["- Wind","null"],["- Light intensity","null"]],["Transpiration stream",["The movement of water through a plant from the roots > through the xylem > to the leaves.","null"]],["BBC Bitesize",["AHREF---http://www.bbc.co.uk.edgesuite.net/education/guides/zps82hv/revision/3","null"],["<iframe src='http://www.bbc.co.uk.edgesuite.net/education/guides/zps82hv/revision/3' width='100%' height='600' scrolling='yes' class='iframe'></iframe>","null"]],["Wikipedia Results - Transpiration",["AHREF---https://en.m.wikipedia.org/wiki/Transpiration","null"],["<iframe src='https://en.m.wikipedia.org/wiki/Transpiration' width='100%' height='600' scrolling='yes' class='iframe'></iframe>","null"]],["Answers.com - What is transpiration",["AHREF---http://www.answers.com/mobile/Q/What_is_xylem","null"],["<iframe src='http://www.answers.com/mobile/Q/What_is_xylem' width='100%' height='600' scrolling='yes' class='iframe'></iframe>","null"]],["Relevant Videos",["VIDEO---https://www.youtube.com/watch?v=mc9gUm1mMzc---Transpiration---From Youtube","null"],["VIDEO---https://www.youtube.com/watch?v=I510WIjaAZk---IGCSE. 2.8 transpiration---From Youtube","null"],["VIDEO---http://v.youku.com/v_show/id_XMTY5OTczNjgxNg==.html?spm=a2h0k.8191407.0.0&from=s1.8-1-1.2---【生物大师】初中生物微课教学视频第38集：蒸腾作用---From Youtube","null"]]]
		,["Tests for nutrients",[["Biology"],"Nutrients and Enzymes"],["IGCSE"],["Introduction",["There are different tests which can be used to detect ...","null"],["- Starch","null"],["- Reducing sugars","null"],["- Proteins","null"],["- Lipids (fats)","http://www.bbc.co.uk/education/guides/z8wsgk7/revision/6"]]]
		,["Transport in humans",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		
		,["The circulatory system",[["Biology"],"Transport in humans"],["IGCSE"],["Introduction",["The circulatory system is the system made up of heart, blood vessels and blood.","null"],["It delivers nutrients and other materials and removes waste products.","null"],["The circulatory system consists of:","null"],["IMG---structure_of_circulatory_system.jpg---500"],[" - tubes: arteries, capillaries and veins","null"],[" - the heart","null"],[" - valves","http://www.bbc.co.uk/education/guides/zhnk7ty/revision/1"]]]
		,["Teeth",[["Biology"],"Digestive system (Topic)"],["IGCSE"],["Introduction",["Food is broken down into smaller pieces in the mouth by <b>chewing</b>.","null"],["This is an example of <b>mechanical digestion</b>.","null"],["The teeth cut and crush food, and the pieces are mixed with <b>saliva</b> to form a ball of food called a <b>bolus</b>.","http://www.bbc.co.uk/education/guides/zwqycdm/revision/2"]]]
		,["Types of human teeth - Incisor Canine Premolar Molar---directTo---Teeth",[["Biology"],"Digestive system (Topic)"],["IGCSE"]]
		,["Tooth decay---directTo---Teeth",[["Biology"],"Digestive system (Topic)"],["IGCSE"]]
		,["The urinary system",[["Biology"],"Excretion in humans"],["IGCSE"],["Introduction",["<b>The urinary syste</b>, is the system consisting of the kidney's, ureters, bladder and urethra.","null"],["The urinaty system works closely with the <b>circulatory system</b>, because the kidneys produce urine by <b>filtering blood</b>.","From Socatic App - Urinary system"]]]
		
		,["The respiratory system",[["Biology"],"The respiratory system (Topic)"],["IGCSE"],["Introduction",["The <b>trachea</b> branches into <b>two bronchi</b> <i style='opacity:0.6;'>(one to each lung)</i>.","null"],["<b>Pleural membranes</b> surround each lung.","null"],["<b>Cartilage rings</b> in the walls of the trachea help to keep it open.","null"],["IMG---the_respiratory_system.jpg---400"],["The bronchi split into smaller and smaller tubes called <b>bronchioles</b>.","null"],["These end in microscopic air sacs called <b>alveoli</b>.","null"],["There is a muscular <b>diaphragm</b> below the lungs.","https://www.bbc.co.uk/education/guides/z6h4jxs/revision/1"]]]
		,["The respiratory system (Topic)",[["Study Set - Topic"],"Biology"],["IGCSE"]]
		,["The nervous system",[["Biology"],"Nervous control"],["IGCSE"],["Introduction",["The human nervous system consists of:","null"],[" - <b>Central nervous system (CNS)</b> - brain and spinal cord, which are the areas of coordination","null"],[" - <b>Peripheral nervous system</b> – made up of nerves and neurones, which coordinate and regulate bodily functions.","From Znotes CIE IGCSE Biology - 14.1 Nervous Control in Humans"],["IMG---the_nervous_system.jpg---300"]]]
		,["Types of neurons",[["Biology"],"Nervous control"],["IGCSE"],["Introduction",["<b>Neurones are the nerve cells.</b>","null"],["There are 3 types of neurones in the nervous system: ","null"],[" - Motor Neurone","null"],[" - Sensory Neurone","null"],[" - Relay (connector) neurone","From Znotes CIE IGCSE Biology - 14.2 Types of Neurons"]]]
		,["The eye",[["Biology"],"Nervous control"],["IGCSE"],["Introduction",["The eye is a sense organ that responds to light.","https://www.bbc.co.uk/education/guides/zkdnb9q/revision/5"]]]
		
		,["The male reproductive system",[["Biology"],"Reproduction in humans"],["IGCSE"],["Introduction",["The male reproductive system consist of:","null"],["IMG---male_reproductive_system.jpg---416"],[" - Testes","null"],[" - Sperm duct","null"],[" - Prostate gland","null"],[" - Penis","null"],[" - Urethra","null"]]]
		,["The female reproductive system",[["Biology"],"Reproduction in humans"],["IGCSE"],["Introduction",["The female reproductive system consist of:","null"],["IMG---female_reproductive_system.jpg---416"],[" - Oviduct","null"],[" - Ovary","null"],[" - Uterus","null"],[" - Cervix","null"],[" - Vagina","null"]]]
		,["The developing embryo",[["Biology"],"Reproduction in humans"],["IGCSE"],["Introduction",["After <b>fertilisation</b>, the newly-formed zygote divides repeatedly to form a <b>ball of cells</b> called an <b>embryo</b>.","null"],["This becomes implanted in the <b>wall</b> of the <b>uterus</b>.","null"],["IMG---embryo.jpg---541"],["After <b>eight weeks</b> of development, the embryo is called a <b>fetus</b>.","https://www.bbc.co.uk/education/guides/z7mbkqt/revision/5"],["The fetus is surronded by amniotic fluid.","null"]]]
		,["The structure of DNA",[["Biology"],"DNA and cell division"],["IGCSE"],["Introduction",["<b>James Watson</b> and <b>Francis Crick</b> worked out the structure of DNA in 1953.","null"],["IMG---dna_under_microscope.jpg---640"],[" -> X-ray diffraction photograph of DNA","null"],["By using data from other scientists they were able to build a <b>model of DNA</b>.","null"],["The <b>X-ray data</b> they used showed that DNA consists of <b>two strands coiled</b> into a double helix.","https://www.bbc.co.uk/education/guides/zvb7hyc/revision/2"]]]
	],

	/*20U*/[
		["Upper epidermis---directTo---Leaf Structure",[["Biology"],"Plant nutrition (Photosynthesis)"],["IGCSE"]]
		,["Urine---directTo---The urinary system",[["Biology"],"Excretion in humans"],["IGCSE"]]
	],
	/*21V*/[
		["Vascular bundle",[["Biology"],"Transport in plants"],["IGCSE"],["Introduction",["Xylem and Phloem are two types of vascular bundle","null"],["A vascular bundle is a part of the transport system in vascular plants, i.e. celery","null"],["IMG---vascularBundle.jpg---480","null"],["It transports food through the xylem and phloem which are located in the vascular tubes.","null"],["When there are lots of vascular tubes bunched together, that is called a vascular bundle.","http://www.answers.com/Q/What_are_vascular_bundles"]],["Function",["The vascular bundles in the plant are like the circulatory system in human.","null"],["They help in the transportation of water,minerals and manufactured food.","null"],["IMG---Vascular_bundle.jpeg---300","null"],["Vascular bundles consist of two types:","null"],[" 1. Xylem which transport water and minerals from the root to the leaf.","null"],[" 2. Phloem which transport manufactured food from the leaf to all plant parts.","null"]],["Wikipedia - Vascular bundle",["AHREF---https://en.m.wikipedia.org/wiki/Vascular_bundle","null"],["<iframe src='https://en.m.wikipedia.org/wiki/Vascular_bundle' width='100%' height='600' scrolling='yes' class='iframe'></iframe>","null"]]]
		,["Veins---directTo---Blood vessels",[["Biology"],"Transport in humans"],["IGCSE"]]
		,["Villi---directTo---Absorption",[["Biology"],"Digestive system (Topic)"],["IGCSE"]]


	],
	/*22W*/[
		["Wind-pollinated flowers---directTo---Pollination",[["Biology"],"Reproduction in plants"],["IGCSE"]]
		,["White blood cells---directTo---Blood",[["Biology"],"Blood (Topic)"],["IGCSE"]]
	],
	/*23X*/[
		["Xylem and Phloem",[["Biology"],"Transport in plants"],["IGCSE"],["Introduction",["IMG---crossSectionXylem_Phloem.png---304","null"],["Xylem and phloem are complex vascular tissues that make up vascular bundles in plants.","null"],["IMG---crossSection_Xylem_Phloem.gif---546","null"],["The purpose of vascular tissue is to effectively transport food, water, and other nutrients throughout the plant.","From Socatic App - Xylem and Phloem"]],["Differences between Xylem and Phloem",["Xylem and phloem share the same goal of transporting materials throughout the plant, but each has its own set of properties.","null"],["IMG---diffxylemphloem.jpg---550","null"],["Xylem carries water and minerals up from the roots, while phloem carries food in both directions (such as sugar).","From Socatic App - Xylem and Phloem"]],["Phloem",["IMG---phloem.jpg---270","null"],["Phloem transports food (sugar) from sources, which are ususally leaves, to growing parts of the plant or storage areas, called sinks. Food moves like an elevator because of sieve plates, which are perforated layers of sieve cells.","http://www.bbc.co.uk.edgesuite.net/education/guides/zps82hv/revision/1"]],["Xylem",["IMG---xylem.jpg---279","null"],["Xylem transports water and minerals in one direction: from root to leaves. Water moves up the plant like a drinking from a straw.","http://www.bbc.co.uk.edgesuite.net/education/guides/zps82hv/revision/1"]],["BBC Bitesize",["AHREF---http://www.bbc.co.uk.edgesuite.net/education/guides/zps82hv/revision/1","null"],["<iframe src='http:www.bbc.co.uk.edgesuite.net/education/guides/zps82hv/revision/1' width='100%' height='600' scrolling='yes' class='iframe'></iframe>","null"]],["Wikipedia Results - Xylem",["AHREF---https://en.m.wikipedia.org/wiki/Xylem","null"],["<iframe src='https://en.m.wikipedia.org/wiki/Xylem' width='100%' height='600' scrolling='yes' class='iframe'></iframe>","null"]],["Wikipedia Results - Phloem",["AHREF---https://en.m.wikipedia.org/wiki/Phloem","null"],["<iframe src='https://en.m.wikipedia.org/wiki/Phloem' width='100%' height='600' scrolling='yes' class='iframe'></iframe>","null"]],["Relevant Videos",["VIDEO---https://www.youtube.com/watch?v=jtuX7H05tmQ---Xylem and Phloem - Transport in Plants | Biology for All | FuseSchool---From Youtube","null"],["VIDEO---https://www.youtube.com/watch?v=Kv_0udatlh8---Xylem and Phloem - Part 2 - Transpiration - Transport in Plants | Biology for All | FuseSchool---From Youtube","null"]]]
	],
	/*24Y*/[],
	/*25Z*/[]

];
